os:
  - linux
  - osx
language: rust
sudo: required
dist: trusty

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 7.7
  - nvm use 7.7
  - npm install

script:
  - npm run test
  - npm run package
